version: "3.8"

services:
  backend:
    image: samjamess/todolist-backend:latest
    restart: always
    environment:
      PORT: ${PORT}
      CONNECTION_URL: ${CONNECTION_URL}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      DEFAULT_CLIENT_URL: ${DEFAULT_CLIENT_URL}
    ports:
      - "3147:3147"

  frontend:
    image: samjamess/todolist-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3148:3148"